name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.10.5 <3.0.0"
  flutter: ">=1.22.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^6.1.14
  http: ^0.12.2
  flutter_spinkit: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.4

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900